// React bileşeninizin içinde bir örnek
fetch('http://localhost:3001/api/todos')
  .then(response => response.json())
  .then(data => {
    console.log(data); // To-do listesi
    // setTodos(data);
  });
